<a href="https://colab.research.google.com/github/Vatsal-Maske/Air-Quality-Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Basic array operation
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
import numpy as np

li = [1,2,3,"hellow"]
lii = [1,2,3]
print(li)

arr= np.array(lij)
print(arr)


[1, 2, 3, 'hellow']
['1' '2' '3' 'hellow']


In [ ]:
arrr=np.array([2,2,3])
print(arrr)

[2 2 3]


## Vectors

In [ ]:
# list does not support multidimensional
l =[[1,2,3],[3,3,4]]

print(l)

[[1, 2, 3], [3, 3, 4]]


In [ ]:
# array support
arr=np.array(l)
print(arr)

[[1 2 3]
 [3 3 4]]


## **Array Genration function**

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
# arr = np.ones(6)
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [ ]:
arr = np.linspace(0,5,100)
arr

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### **Random Generating Function**

In [ ]:
np.random.rand(10)
# 1-0 ke bich me hi milegi this normalization

array([0.59375113, 0.74079257, 0.95652646, 0.35432506, 0.72277452,
       0.52623449, 0.21355127, 0.03311876, 0.08631807, 0.24615824])

In [ ]:
np.random.randn(10)

array([-2.33371499, -0.16164216,  2.6640165 , -0.62695969,  0.65119133,
        0.08272107,  0.49360259,  0.54161922,  0.264558  ,  2.14373659])

In [ ]:
np.random.randint(10,20,10)

array([10, 18, 17, 15, 19, 13, 18, 15, 10, 17])

## **Array atributes**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
# arr.dtype

dtype('int64')

### **Array Methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
print(arr.std())


2.581988897471611


In [ ]:
print(arr.argmax())

8


In [ ]:
print(arr.argmin())

0


In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr
arr.resize()
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## **Indexing and Slicing**

In [ ]:
arr=np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr[6]
print(arr[6])

17


In [ ]:
print(arr[9])

20


In [ ]:
print(arr[0:6])

[11 12 13 14 15 16]


In [ ]:
print(arr[1:4])

## **Numpy Indexing ans Slicing of matrix**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
print(arr[0,4])
l

5


### **Slicing **

In [ ]:
import numpy as np

arr = np.arange(11,21);
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr[4]

np.int64(15)

In [ ]:
# Numpy indexing ans Slicing

arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]
arr[1]
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
print(arr[0,0])
print(arr[0,4])
print(arr[5,4])

1
5
30


In [ ]:
slice = arr[0:2,1:3]

slice = arr [3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25],
#        [26, 27, 28, 29, 30]])
arr[1:3,2:]
arr[2:5:2,1:4]

array([[12, 13, 14],
       [22, 23, 24]])

### Boolean indexing

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
boolindex = arr%2 == 0
boolindex

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[boolindex]
arr

array([12, 14, 16, 18, 20])

### **Array Operartion**

In [ ]:
import numpy as np

In [ ]:
# size of an array shou=ould be same
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [ ]:
l= [10,20,30,40]
arr = np.array(l)

In [ ]:
arr+10

array([22, 24, 26, 28, 30])

### deep and Shallow **copy**

In [ ]:
arr2=np.arange(1,26).reshape(5,5)

arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
a = np.arange(1,21)
slice = a[:5]
slice = slice*10;
slice
# dekho agar me isme slice ko =kuch chanjge karrra hu to mere main array me nahi honga byt azgar me isme karat hojayenga to dekh ke karana



array([10, 20, 30, 40, 50])

In [ ]:
li = [1,2,3,4,6]
li[:4]*10

print(li)

[1, 2, 3, 4, 6]


# **matrix operation**

In [ ]:
# matrix multiplication
# a @ b kardena 2 matrix ka multiplication hojayega
# or we can use np.dot(a,b)
# transpose karne ke liye A.T likhan t ransopse karta hai or A matrix hai

Stacking

In [ ]:
# we have to use vectors not matrix

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
c =np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [1]:
!git branch

fatal: not a git repository (or any of the parent directories): .git
